/**
 * @file application_failure.h
 * @brief Stable protocol failure provenance, independent of firmware enums.
 * @details Schema 1 accepts only assigned values. NONE requires all three
 * fields NONE; a nonzero reason requires nonzero source and stage. Capture the
 * first failure stage when it occurs, and map native failures explicitly.
 */
#ifndef HIL_RIG_PROTOCOL_APPLICATION_APPLICATION_FAILURE_H
#define HIL_RIG_PROTOCOL_APPLICATION_APPLICATION_FAILURE_H

/** Stable failure source; wire width one byte. */
typedef enum
{
    HIL_APPLICATION_FAILURE_SOURCE_NONE              = 0x0,
    HIL_APPLICATION_FAILURE_SOURCE_RUN_STATE_MANAGER = 0x1,
    HIL_APPLICATION_FAILURE_SOURCE_EXECUTION_MANAGER = 0x2,
    HIL_APPLICATION_FAILURE_SOURCE_FLASH_MANAGER     = 0x3,
    HIL_APPLICATION_FAILURE_SOURCE_HOST_INTERFACE    = 0x4,
    HIL_APPLICATION_FAILURE_SOURCE_DRIVER_LIFECYCLE  = 0x5,
    HIL_APPLICATION_FAILURE_SOURCE_EXECUTION_TIMER   = 0x6,
} HIL_Application_Failure_Source_T;

/** Stable failure stage; wire width one byte. */
typedef enum
{
    HIL_APPLICATION_FAILURE_STAGE_NONE         = 0x0,
    HIL_APPLICATION_FAILURE_STAGE_PREPARATION  = 0x1,
    HIL_APPLICATION_FAILURE_STAGE_EXECUTION    = 0x2,
    HIL_APPLICATION_FAILURE_STAGE_SHUTDOWN     = 0x3,
    HIL_APPLICATION_FAILURE_STAGE_FINALISATION = 0x4,
    HIL_APPLICATION_FAILURE_STAGE_TRANSFER     = 0x5,
    HIL_APPLICATION_FAILURE_STAGE_CLEANUP      = 0x6,
} HIL_Application_Failure_Stage_T;

/** Stable failure reason; wire width two bytes. */
typedef enum
{
    HIL_APPLICATION_FAILURE_REASON_NONE                            = 0x0,
    HIL_APPLICATION_FAILURE_REASON_HOST_ABORT                      = 0x1,
    HIL_APPLICATION_FAILURE_REASON_APPLICATION_RESET               = 0x2,
    HIL_APPLICATION_FAILURE_REASON_INVALID_LIFECYCLE_STATE         = 0x10,
    HIL_APPLICATION_FAILURE_REASON_HARDWARE_NOT_READY              = 0x11,
    HIL_APPLICATION_FAILURE_REASON_CONFIGURATION_UNAVAILABLE       = 0x12,
    HIL_APPLICATION_FAILURE_REASON_DRIVER_CONFIGURATION_FAILED     = 0x20,
    HIL_APPLICATION_FAILURE_REASON_DRIVER_CONFIGURATION_TIMEOUT    = 0x21,
    HIL_APPLICATION_FAILURE_REASON_DRIVER_START_FAILED             = 0x22,
    HIL_APPLICATION_FAILURE_REASON_DRIVER_START_TIMEOUT            = 0x23,
    HIL_APPLICATION_FAILURE_REASON_DRIVER_STOP_FAILED              = 0x24,
    HIL_APPLICATION_FAILURE_REASON_DRIVER_STOP_TIMEOUT             = 0x25,
    HIL_APPLICATION_FAILURE_REASON_ACQUISITION_EPOCH_FAILED        = 0x30,
    HIL_APPLICATION_FAILURE_REASON_EXECUTION_TIMER_FAILED          = 0x31,
    HIL_APPLICATION_FAILURE_REASON_EXECUTION_NOT_PREPARED          = 0x40,
    HIL_APPLICATION_FAILURE_REASON_INSTRUCTION_UNDERRUN            = 0x41,
    HIL_APPLICATION_FAILURE_REASON_INSTRUCTION_CORRUPT             = 0x42,
    HIL_APPLICATION_FAILURE_REASON_INSTRUCTION_LATE                = 0x43,
    HIL_APPLICATION_FAILURE_REASON_OPERATION_REJECTED              = 0x44,
    HIL_APPLICATION_FAILURE_REASON_INSTRUCTION_CONSUME_FAILED      = 0x45,
    HIL_APPLICATION_FAILURE_REASON_MEASUREMENT_REJECTED            = 0x46,
    HIL_APPLICATION_FAILURE_REASON_INSTRUCTION_UNCONSUMED          = 0x47,
    HIL_APPLICATION_FAILURE_REASON_FLASH_PREPARATION_FAILED        = 0x50,
    HIL_APPLICATION_FAILURE_REASON_FLASH_PREPARATION_TIMEOUT       = 0x51,
    HIL_APPLICATION_FAILURE_REASON_FLASH_FINALISATION_FAILED       = 0x52,
    HIL_APPLICATION_FAILURE_REASON_FLASH_FINALISATION_TIMEOUT      = 0x53,
    HIL_APPLICATION_FAILURE_REASON_RESULT_TRANSFER_FAILED          = 0x54,
    HIL_APPLICATION_FAILURE_REASON_RESULT_DISPOSITION_FAILED       = 0x55,
    HIL_APPLICATION_FAILURE_REASON_FLASH_MANAGER_FAILED            = 0x56,
    HIL_APPLICATION_FAILURE_REASON_HOST_RESPONSE_BLOCKED           = 0x60,
    HIL_APPLICATION_FAILURE_REASON_INSTRUCTION_UPLOAD_TIMEOUT      = 0x61,
    HIL_APPLICATION_FAILURE_REASON_USB_INITIALISATION_FAILED       = 0x62,
    HIL_APPLICATION_FAILURE_REASON_CODEC_INITIALISATION_FAILED     = 0x63,
    HIL_APPLICATION_FAILURE_REASON_TRANSPORT_INITIALISATION_FAILED = 0x64,
    HIL_APPLICATION_FAILURE_REASON_HOST_INTERFACE_FAILED           = 0x65,
    HIL_APPLICATION_FAILURE_REASON_INTERNAL_FAILURE                = 0x70,
} HIL_Application_Failure_Reason_T;

#endif
