"""Supported Python interface for the HIL-RIG protocol.

This release provides the complete caller-driven Transport facade, including
validated configuration, native lifetime ownership, encoded I/O servicing,
opaque Application data, events, and status snapshots. ApplicationCodec provides
stateless native encoding/decoding for complete Test Configuration and fixed
Digital, Analog and PWM Test Instruction/Result messages.
"""

from .application import ApplicationCodec
from .application_types import (
    AnalogInputConfig,
    AnalogInputValue,
    AnalogOutputConfig,
    AnalogOutputValue,
    ApplicationConfig,
    ApplicationMessage,
    ApplicationStatus,
    BusRole,
    CANConfig,
    DigitalInputConfig,
    DigitalInputValue,
    DigitalOutputConfig,
    DigitalOutputValue,
    I2CConfig,
    I2CPullUp,
    I2CVoltage,
    PeripheralVoltage,
    PWMInputConfig,
    PWMInputValue,
    PWMOutputConfig,
    PWMOutputValue,
    ResultCondition,
    SPIBitOrder,
    SPIClockPhase,
    SPIClockPolarity,
    SPIConfig,
    SPIDataWidth,
    TestConfiguration,
    TestId,
    TestInstruction,
    TestResult,
    TickDuration,
    UARTConfig,
    UARTElectricalMode,
    UARTParity,
    UARTStopBits,
    UARTWordLength,
)
from .errors import (
    ApplicationBindingError,
    ApplicationConfigurationError,
    ApplicationDecodeError,
    ApplicationEncodeError,
    ApplicationError,
    ApplicationInternalError,
    ApplicationOwnershipError,
    ProtocolError,
    TransportBindingError,
    TransportClosedError,
    TransportConfigurationError,
    TransportCreationError,
    TransportError,
    TransportInternalError,
    TransportOwnershipError,
)
from .transport import Transport
from .transport_types import (
    EventType,
    Failure,
    LinkState,
    OperatingMode,
    ReceiveResult,
    Role,
    SessionState,
    TransportConfig,
    TransportEvent,
    TransportSnapshot,
    TransportStatus,
)

__all__ = [
    "ApplicationCodec",
    "ApplicationStatus",
    "PeripheralVoltage",
    "BusRole",
    "SPIDataWidth",
    "SPIBitOrder",
    "SPIClockPolarity",
    "SPIClockPhase",
    "UARTElectricalMode",
    "UARTWordLength",
    "UARTParity",
    "UARTStopBits",
    "I2CVoltage",
    "I2CPullUp",
    "ResultCondition",
    "TestId",
    "TickDuration",
    "DigitalOutputValue",
    "DigitalInputValue",
    "AnalogOutputValue",
    "AnalogInputValue",
    "PWMOutputValue",
    "PWMInputValue",
    "DigitalInputConfig",
    "DigitalOutputConfig",
    "AnalogInputConfig",
    "AnalogOutputConfig",
    "PWMInputConfig",
    "PWMOutputConfig",
    "CANConfig",
    "SPIConfig",
    "UARTConfig",
    "I2CConfig",
    "ApplicationConfig",
    "TestConfiguration",
    "TestInstruction",
    "TestResult",
    "ApplicationMessage",
    "ApplicationError",
    "ApplicationConfigurationError",
    "ApplicationEncodeError",
    "ApplicationDecodeError",
    "ApplicationBindingError",
    "ApplicationOwnershipError",
    "ApplicationInternalError",
    "ProtocolError",
    "TransportError",
    "TransportConfigurationError",
    "TransportCreationError",
    "TransportBindingError",
    "TransportClosedError",
    "TransportOwnershipError",
    "TransportInternalError",
    "TransportStatus",
    "Role",
    "LinkState",
    "OperatingMode",
    "SessionState",
    "Failure",
    "EventType",
    "TransportConfig",
    "ReceiveResult",
    "TransportEvent",
    "TransportSnapshot",
    "Transport",
]
