#include "hil_rig_protocol/version.h"

#include <gtest/gtest.h>

#include <cstring>

TEST( Version, GeneratedMacrosAndFunctionsMatchCMakeProjectVersion )
{
    EXPECT_EQ( HIL_RIG_PROTOCOL_VERSION_MAJOR, HIL_RIG_PROTOCOL_TEST_VERSION_MAJOR );
    EXPECT_EQ( HIL_RIG_PROTOCOL_VERSION_MINOR, HIL_RIG_PROTOCOL_TEST_VERSION_MINOR );
    EXPECT_EQ( HIL_RIG_PROTOCOL_VERSION_PATCH, HIL_RIG_PROTOCOL_TEST_VERSION_PATCH );
    EXPECT_STREQ( HIL_RIG_PROTOCOL_VERSION_STRING, HIL_RIG_PROTOCOL_TEST_VERSION_STRING );

    EXPECT_EQ( HIL_RIG_PROTOCOL_Version_Major(), HIL_RIG_PROTOCOL_VERSION_MAJOR );
    EXPECT_EQ( HIL_RIG_PROTOCOL_Version_Minor(), HIL_RIG_PROTOCOL_VERSION_MINOR );
    EXPECT_EQ( HIL_RIG_PROTOCOL_Version_Patch(), HIL_RIG_PROTOCOL_VERSION_PATCH );
    EXPECT_STREQ( HIL_RIG_PROTOCOL_Version_String(), HIL_RIG_PROTOCOL_VERSION_STRING );
}
